server:
  gzip:
    enabled: true
    bufferSize: 8KiB
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 9001
  requestLog:
    appenders: []
configPath: /etc/sidewinder/sidewinder.properties